cn_chemcloud/ChemCloud.Web/Areas/SellerAdmin/Controllers/CustomerServiceController.cs
using ChemCloud.IServices;
using ChemCloud.Model;
using ChemCloud.Web.Areas.SellerAdmin.Models;
using ChemCloud.Web.Framework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.CompilerServices;
using System.Web.Mvc;

namespace ChemCloud.Web.Areas.SellerAdmin.Controllers
{
	public class CustomerServiceController : BaseSellerController
	{
		public CustomerServiceController()
		{
		}

		public ActionResult Add(long? id)
		{
			CustomerServiceInfo customerServiceInfo;
			CustomerServiceModel customerServiceModel;
			ICustomerService customerService = ServiceHelper.Create<ICustomerService>();
			if (id.HasValue)
			{
				long? nullable = id;
				if ((nullable.GetValueOrDefault() <= 0 ? true : !nullable.HasValue))
				{
					customerServiceInfo = new CustomerServiceInfo();
					customerServiceModel = new CustomerServiceModel()
					{
						Id = customerServiceInfo.Id,
						Account = customerServiceInfo.AccountCode,
						Name = customerServiceInfo.Name,
						Tool = customerServiceInfo.Tool,
						Type = new CustomerServiceInfo.ServiceType?(customerServiceInfo.Type)
					};
					return View(customerServiceModel);
				}
				customerServiceInfo = customerService.GetCustomerService(base.CurrentSellerManager.ShopId, id.Value);
				customerServiceModel = new CustomerServiceModel()
				{
					Id = customerServiceInfo.Id,
					Account = customerServiceInfo.AccountCode,
					Name = customerServiceInfo.Name,
					Tool = customerServiceInfo.Tool,
					Type = new CustomerServiceInfo.ServiceType?(customerServiceInfo.Type)
				};
				return View(customerServiceModel);
			}
			customerServiceInfo = new CustomerServiceInfo();
			customerServiceModel = new CustomerServiceModel()
			{
				Id = customerServiceInfo.Id,
				Account = customerServiceInfo.AccountCode,
				Name = customerServiceInfo.Name,
				Tool = customerServiceInfo.Tool,
				Type = new CustomerServiceInfo.ServiceType?(customerServiceInfo.Type)
			};
			return View(customerServiceModel);
		}

		[HttpPost]
		[UnAuthorize]
		public JsonResult Add(CustomerServiceModel customerServiceModel)
		{
			ICustomerService customerService = ServiceHelper.Create<ICustomerService>();
			CustomerServiceInfo customerServiceInfo = new CustomerServiceInfo()
			{
				Id = customerServiceModel.Id,
				Type = customerServiceModel.Type.GetValueOrDefault(CustomerServiceInfo.ServiceType.PreSale),
				Tool = customerServiceModel.Tool,
				Name = customerServiceModel.Name,
				AccountCode = customerServiceModel.Account,
				ShopId = base.CurrentSellerManager.ShopId
			};
			CustomerServiceInfo customerServiceInfo1 = customerServiceInfo;
			if (customerServiceInfo1.Id <= 0)
			{
				customerService.AddCustomerService(customerServiceInfo1);
			}
			else
			{
				customerService.UpdateCustomerService(customerServiceInfo1);
			}
			return Json(new { success = true });
		}

		[HttpPost]
		[UnAuthorize]
		public JsonResult Delete(long id)
		{
			ServiceHelper.Create<ICustomerService>().DeleteCustomerService(base.CurrentSellerManager.ShopId, new long[] { id });
			return Json(new { success = true });
		}

		public ActionResult Management()
		{
			CustomerServiceInfo[] array = (
				from item in ServiceHelper.Create<ICustomerService>().GetCustomerService(base.CurrentSellerManager.ShopId)
				orderby item.Id descending
				select item).ToArray();
			IEnumerable<CustomerServiceModel> customerServiceModel = 
				from item in array
                select new CustomerServiceModel()
				{
					Id = item.Id,
					Account = item.AccountCode,
					Name = item.Name,
					Tool = item.Tool,
					Type = new CustomerServiceInfo.ServiceType?(item.Type)
				};
			return View(customerServiceModel);
		}
	}
}

cn_chemcloud/ChemCloud.Web/Areas/SellerAdmin/Views/CustomerService/Add.cshtml
@using ChemCloud.Core;
@model ChemCloud.Web.Areas.SellerAdmin.Models.CustomerServiceModel
<div class="container">
    <ul class="nav nav-tabs-custom clearfix">
        <strong>客服管理</strong>
        <li><a href="management">管理</a></li>
        <li class="active"><a>@(Model.Id > 0 ? "编辑" : "新增")</a></li>
    </ul>
    <form class="form-horizontal" role="form">
        <div class="form-group">
            <label for="" class="col-sm-2 control-label"><b>*</b>客服名称：</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control input-sm", maxlength = 15 })
            </div>
            <div class="col-sm-3">
                @Html.ValidationMessageFor(m => m.Name, "", new { @class = "help-default cor-red" })
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 control-label"><b>*</b>沟通工具：</label>
            <div class="col-sm-3">
                @Html.DropDownListFor(s => s.Tool, ((IEnumerable<SelectListItem>)ChemCloud.Model.CustomerServiceInfo.ServiceTool.QQ.ToSelectList(false)), new { @class = "form-control input-sm" })
            </div>
        </div>

        <div class="form-group">
            <label for="" class="col-sm-2 control-label"><b>*</b>账号：</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.Account, new { @class = "form-control input-sm", maxlength = 25 })
            </div>
            <div class="col-sm-3">
                @Html.ValidationMessageFor(m => m.Account, "", new { @class = "help-default cor-red" })
            </div>
        </div>

        <div class="form-group">
            <label for="" class="col-sm-2 control-label"><b>*</b>账号：</label>
            <div class="col-sm-3">
                <label> <input type="radio" name="type" value="1" @((Model.Type.HasValue || Model.Type == ChemCloud.Model.CustomerServiceInfo.ServiceType.PreSale) ? "checked" : "") />售前</label>
                <label> <input type="radio" name="type" value="2" @(Model.Type == ChemCloud.Model.CustomerServiceInfo.ServiceType.AfterSale ? "checked" : "") />售后</label>
            </div>
        </div>

        @Html.HiddenFor(m => m.Id)
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="button" class="btn btn-primary" id="submit">保 存</button>
            </div>
        </div>
    </form>
</div>

<script>
$(function(){
$("#Name").focus();
});
    function bindSubmitClickEvent() {
        var form = $('form');
        $('#submit').click(function () {
            if (form.valid()) {
                var loading = showLoading();
                $.post('add', form.serialize(), function (result) {
                    loading.close();
                    if (result.success) {
                        $.dialog.tips('保存成功', function () {
                            location.href = '@Url.Action("management", "CustomerService", new {area="Selleradmin"})';
                        });
                    }
                    else
                        $.dialog.errorTips('保存失败!' + result.msg);
                })
            }
        });
    }


    $(function () {
        bindSubmitClickEvent();


    })



</script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

cn_chemcloud/ChemCloud.Web/Areas/SellerAdmin/Views/CustomerService/Management.cshtml
@model IEnumerable<ChemCloud.Web.Areas.SellerAdmin.Models.CustomerServiceModel>
@using ChemCloud.Core;

<div class="container">
    <ul class="nav nav-tabs-custom clearfix">
        <strong>客服管理</strong>
        <li class="active"><a>管理</a></li>
        <li><a href="add">新增</a></li>
        <em class="primary-btn">
            <span class="glyphicon glyphicon-question-sign"></span>
            <div class="primary">
                <h3>温馨提示：</h3>
                <span>*</span><p>管理供应商客服，可设置不同的沟通工具及客服类型</p>
            </div>
        </em>
    </ul>

    <table class="table mt20">
        <thead>
            <tr>
                <th>客服名称</th>
                <th style="text-align:center">沟通工具</th>
                <th style="text-align:center">账号</th>
                <th style="text-align:center">客服类型</th>
                <th class="td-operate">操作</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var customerService in Model)
            {
                <tr>
                    <td>@customerService.Name</td>
                    <td align="center">@customerService.Tool.ToDescription()</td>
                    <td align="center">@customerService.Account</td>
                    <td align="center">@customerService.Type.ToDescription()</td>
                    <td class="td-operate">
                        <span class="btn-a">
                             <a href="add?id=@customerService.Id">编辑</a>
                             <a onclick="del(@customerService.Id,'@customerService.Name')">删除</a>
                        </span>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<script>

    function del(id,name) {
        $.dialog.confirm('确定要删除客服 '+name+' 吗？',function(){
            var loading = showLoading();
            $.post('delete',{id:id},function(result){
                loading.close();
                if(result.success)
                    $.dialog.succeedTips('删除成功!',function(){location.href=location.href});
                else
                    $.dialog.errorTips('删除失败！'+result.msg);
            });
        });
    }

</script>